import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

import Header from "@/components/Header";
import Providers from "@/utils/Providers";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "50b ZK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={`pt-12 bg-gray-900 h-screen overflow-y-auto overflow-x-hidden ${inter.className}`}
        >
          <Header />
          {children}
          <ToastContainer theme="dark" />
        </body>
      </html>
    </Providers>
  );
}
